export const STORY_LIST_REQUEST = "STORY_LIST_REQUEST";
export const STORY_LIST_SUCCESS = "STORY_LIST_SUCCESS";
export const STORY_LIST_FAIL = "STORY_LIST_FAIL";
export const STORY_DETAILS_REQUEST = "STORY_DETAILS_REQUEST";
export const STORY_DETAILS_SUCCESS = "STORY_DETAILS_SUCCESS";
export const STORY_DETAILS_FAIL = "STORY_DETAILS_FAIL";

